########################Don`t Fix Me###############################
_Prj_Name: "test_prj"
_Trace_Type: "trace_type"
###################################################################

TestKv : "TestKvVal"

TestMap:
    k1 : "v1"
    k2 : "v2"

TestSlice:
    - "s1"
    - "s2"

